services:
  lrctl: 
    image: gcr.io/lrcollection/lrctl
    version: 0.1.33
  open-collector:  
    image: gcr.io/lrcollection/opencollector
    version: 0.1.26
  metrics:  
    image: gcr.io/lrcollection/metrics
    version: 0.3.0
  eventhubbeat:  
    image: gcr.io/lrcollection/beats/eventhubbeat
    version: 2.0.2
  gsbeat:
    image: gcr.io/lrcollection/beats/gsbeat
    version: 0.1.3
  s3beat:
    image: gcr.io/lrcollection/beats/s3beat
    version: 0.1.2
  pubsubbeat:
    image: gcr.io/lrcollection/beats/pubsubbeat
    version: 1.2.8
  sophoscentralbeat:
    image: gcr.io/lrcollection/beats/sophoscentralbeat 
    version: 1.0.1
  gmtbeat:
    image: gcr.io/lrcollection/beats/gmtbeat
    version: 0.1.2
utilities:
  lrjq:
    image: gcr.io/lrcollection/lrjq
    version: 0.1.2
  ocpipeline:
    image: gcr.io/lrcollection/ocpipeline
    version: 0.1.3
    
